"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import {
  Coupon,
  createCoupon,
  getApiErrorMessage,
  updateCoupon,
} from "@/app/lib/couponService";

type CouponFormValues = {
  discount: string;
  maxUses: string;
  minOrderAmount: string;
  noMinimumOrder: boolean;
  maxUsesPerUser: string;
  isActive: boolean;
};

type CouponFormProps = {
  mode: "create" | "edit";
  couponId?: string;
  initialCoupon?: Coupon;
};

function formatDateTime(value: string | null | undefined) {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleString("en-GB", {
    year: "numeric",
    month: "short",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export default function CouponForm({ mode, couponId, initialCoupon }: CouponFormProps) {
  const router = useRouter();
  const isArchived = initialCoupon?.status === "archived";
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState<Partial<Record<keyof CouponFormValues, string>>>({});
  const [values, setValues] = useState<CouponFormValues>({
    discount: String(initialCoupon?.discount ?? ""),
    maxUses: String(initialCoupon?.maxUses ?? ""),
    minOrderAmount: String(initialCoupon?.minOrderAmount ?? 0),
    noMinimumOrder: initialCoupon?.minOrderAmount === null,
    maxUsesPerUser: String(initialCoupon?.maxUsesPerUser ?? ""),
    isActive: initialCoupon?.isActive ?? true,
  });

  const pageTitle = mode === "create" ? "Create Coupon" : "Edit Coupon";

  const parsedValues = useMemo(
    () => ({
      discount: Number(values.discount),
      maxUses: Number(values.maxUses),
      minOrderAmount: Number(values.minOrderAmount),
      maxUsesPerUser: Number(values.maxUsesPerUser),
    }),
    [values],
  );

  const validate = () => {
    const nextErrors: Partial<Record<keyof CouponFormValues, string>> = {};

    if (!Number.isFinite(parsedValues.discount) || parsedValues.discount <= 0) {
      nextErrors.discount = "Discount must be greater than 0.";
    }
    if (!Number.isFinite(parsedValues.maxUses) || parsedValues.maxUses < 1) {
      nextErrors.maxUses = "Max uses must be at least 1.";
    }
    if (
      !Number.isFinite(parsedValues.maxUsesPerUser) ||
      parsedValues.maxUsesPerUser < 1
    ) {
      nextErrors.maxUsesPerUser = "Max uses per user must be at least 1.";
    }
    if (
      !values.noMinimumOrder &&
      (!Number.isFinite(parsedValues.minOrderAmount) || parsedValues.minOrderAmount < 0)
    ) {
      nextErrors.minOrderAmount = "Min order amount must be 0 or greater.";
    }

    setErrors(nextErrors);
    return Object.keys(nextErrors).length === 0;
  };

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (mode === "edit" && isArchived) {
      toast.error("Archived coupons cannot be edited.");
      return;
    }

    if (!validate()) return;

    setIsSubmitting(true);
    try {
      const payload = {
        discount: parsedValues.discount,
        maxUses: parsedValues.maxUses,
        minOrderAmount: values.noMinimumOrder ? null : parsedValues.minOrderAmount,
        maxUsesPerUser: parsedValues.maxUsesPerUser,
        isActive: values.isActive,
      };

      if (mode === "create") {
        const created = await createCoupon(payload);
        toast.success(`Coupon created: ${created.code}`);
      } else if (couponId) {
        await updateCoupon(couponId, payload);
        toast.success("Coupon updated successfully.");
      }
      router.push("/coupons");
      router.refresh();
    } catch (error) {
      const fallback =
        mode === "create" ? "Failed to create coupon." : "Failed to update coupon.";
      toast.error(getApiErrorMessage(error, fallback));
    } finally {
      setIsSubmitting(false);
    }
  };

  const disabled = isSubmitting || (mode === "edit" && isArchived);

  return (
    <div className="mx-auto w-full max-w-4xl px-4 py-6 md:px-8">
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-gray-900">{pageTitle}</h1>
        <p className="text-sm text-gray-500">
          {mode === "create"
            ? "Coupon code is generated by the server automatically."
            : "Update coupon settings and limits."}
        </p>
      </div>

      {mode === "edit" && initialCoupon ? (
        <div className="mb-4 grid gap-3 rounded-xl border border-gray-200 bg-white p-4 md:grid-cols-2">
          <div>
            <p className="text-xs uppercase text-gray-500">Code</p>
            <p className="text-sm font-medium text-gray-900">{initialCoupon.code || "-"}</p>
          </div>
          <div>
            <p className="text-xs uppercase text-gray-500">Uses</p>
            <p className="text-sm font-medium text-gray-900">
              {initialCoupon.uses} / {initialCoupon.maxUses}
            </p>
          </div>
          <div>
            <p className="text-xs uppercase text-gray-500">Status</p>
            <p className="text-sm font-medium text-gray-900">{initialCoupon.status}</p>
          </div>
          <div>
            <p className="text-xs uppercase text-gray-500">Archived At</p>
            <p className="text-sm font-medium text-gray-900">
              {formatDateTime(initialCoupon.archivedAt)}
            </p>
          </div>
          <div className="md:col-span-2">
            <p className="text-xs uppercase text-gray-500">Archived Reason</p>
            <p className="text-sm font-medium text-gray-900">
              {initialCoupon.archivedReason || "-"}
            </p>
          </div>
        </div>
      ) : null}

      {isArchived ? (
        <div className="mb-4 rounded-lg border border-amber-300 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          This coupon is archived and cannot be edited.
        </div>
      ) : null}

      <form
        onSubmit={handleSubmit}
        className="grid gap-4 rounded-xl border border-gray-200 bg-white p-4 md:grid-cols-2"
      >
        <label className="flex flex-col gap-1">
          <span className="text-sm text-gray-700">Discount</span>
          <input
            type="number"
            min="0"
            step="0.01"
            value={values.discount}
            onChange={(event) => setValues((prev) => ({ ...prev, discount: event.target.value }))}
            disabled={disabled}
            className="rounded-lg border border-gray-200 px-3 py-2 text-sm outline-none focus:border-gray-900 disabled:bg-gray-50"
          />
          {errors.discount ? <span className="text-xs text-red-600">{errors.discount}</span> : null}
        </label>

        <label className="flex flex-col gap-1">
          <span className="text-sm text-gray-700">Max Uses</span>
          <input
            type="number"
            min="1"
            step="1"
            value={values.maxUses}
            onChange={(event) => setValues((prev) => ({ ...prev, maxUses: event.target.value }))}
            disabled={disabled}
            className="rounded-lg border border-gray-200 px-3 py-2 text-sm outline-none focus:border-gray-900 disabled:bg-gray-50"
          />
          {errors.maxUses ? <span className="text-xs text-red-600">{errors.maxUses}</span> : null}
        </label>

        <label className="flex flex-col gap-1">
          <span className="text-sm text-gray-700">Min Order Amount</span>
          <div className="mb-1 flex items-center gap-2">
            <input
              type="checkbox"
              checked={values.noMinimumOrder}
              onChange={(event) =>
                setValues((prev) => ({ ...prev, noMinimumOrder: event.target.checked }))
              }
              disabled={disabled}
              className="size-4 rounded border-gray-300"
            />
            <span className="text-xs text-gray-600">No minimum order</span>
          </div>
          <input
            type="number"
            min="0"
            step="0.01"
            value={values.minOrderAmount}
            onChange={(event) =>
              setValues((prev) => ({ ...prev, minOrderAmount: event.target.value }))
            }
            disabled={disabled || values.noMinimumOrder}
            className="rounded-lg border border-gray-200 px-3 py-2 text-sm outline-none focus:border-gray-900 disabled:bg-gray-50"
          />
          {errors.minOrderAmount ? (
            <span className="text-xs text-red-600">{errors.minOrderAmount}</span>
          ) : null}
        </label>

        <label className="flex flex-col gap-1">
          <span className="text-sm text-gray-700">Max Uses Per User</span>
          <input
            type="number"
            min="1"
            step="1"
            value={values.maxUsesPerUser}
            onChange={(event) =>
              setValues((prev) => ({ ...prev, maxUsesPerUser: event.target.value }))
            }
            disabled={disabled}
            className="rounded-lg border border-gray-200 px-3 py-2 text-sm outline-none focus:border-gray-900 disabled:bg-gray-50"
          />
          {errors.maxUsesPerUser ? (
            <span className="text-xs text-red-600">{errors.maxUsesPerUser}</span>
          ) : null}
        </label>

        <label className="flex items-center gap-2 pt-7">
          <input
            type="checkbox"
            checked={values.isActive}
            onChange={(event) => setValues((prev) => ({ ...prev, isActive: event.target.checked }))}
            disabled={disabled}
            className="size-4 rounded border-gray-300"
          />
          <span className="text-sm text-gray-700">Active</span>
        </label>

        <div className="md:col-span-2 mt-2 flex items-center gap-2">
          <button
            type="button"
            onClick={() => router.push("/coupons")}
            disabled={isSubmitting}
            className="rounded-lg border border-gray-200 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50 disabled:cursor-not-allowed disabled:opacity-60"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={disabled}
            className="rounded-lg bg-gray-900 px-4 py-2 text-sm font-medium text-white hover:bg-black disabled:cursor-not-allowed disabled:opacity-60"
          >
            {isSubmitting
              ? mode === "create"
                ? "Creating..."
                : "Saving..."
              : mode === "create"
                ? "Create Coupon"
                : "Save Changes"}
          </button>
        </div>
      </form>
    </div>
  );
}
